project-board:
  name: 'Pipeline for QA'
  contributor-column-name: 'CONTRIBUTOR'
  review-column-name: 'REVIEW'
  test-column-name: 'TO TEST'

bounty-project-board:
  name: 'Status SOB Swarm'
  label-name: 'bounty-awaiting-approval'
  awaiting-approval-column-name: 'bounty-awaiting-approval'

welcome-bot:
  message: 'Thanks for making your first PR here!'

github:
  slack-mapping:
    # - github: slack
    martinklepsch: slack

slack:
  notification:
    room: 'status-probot'